### ISSUE TITLE
for discussion: also upgrade npx with dist-upgrade?

### ISSUE THREAD

**Issue by junosuarez** [zacanger/dist-upgrade#6]
`npx` is now bundled with `npm`, which is great because so many more people have it available by default and can take advantage of the workflows it enables.

However, just like the node.js installer doesn't always have the latest version of `npm`, the `npm` installer doesn't always have the latest version of `npx`.

`dist-upgrade` is great for people who always want to be on the bleeding edge. Does it make sense to also do an `npm i -g npx` when running `dist-upgrade`?

**Comment by zautumnz** [comment]
That definitely makes sense, since it's already installing latest Node instead of LTS and `npm@next`. I can make that change today, unless you wanted to?

**Comment by zautumnz** [comment]
Added installing `npx` in 0.3.0 :)
